version: "3.3"
services:
  db:
    image: mariadb:10.4
    container_name: dress_me
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db:/var/db
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dev
    ports:
      - "3309:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_dress_me
    depends_on:
      - db
    ports:
      - 81:80
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 100M
    networks:
      - dev

  mailpit:
    image: axllent/mailpit
    container_name: mailpit_docker_dress_me
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - dev

  www:
    build: ./docker/php
    container_name: www_docker_dress_me
    depends_on:
      - db
      - mailpit
    ports:
      - "80:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www
      - ./tmp:/tmp
    networks:
      - dev

  messenger:
    build: ./docker/php
    container_name: messenger_docker_dress_me
    depends_on:
      - db
      - mailpit
    command: php bin/console messenger:consume async --time-limit=3600 --memory-limit=256M -vv
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./tmp:/tmp
    networks:
      - dev

  redis:
    image: redis:6-alpine
    networks:
      - dev
    sysctls:
      - "net.core.somaxconn=511"
    ports:
      - 6379:6379

networks:
  dev:

volumes:
  db-data:
